### ISSUE TITLE
Requiring optional fields.  

### ISSUE THREAD

**Issue by dwastberg** [mrcagney/gtfstk#10]
Hi 

compute_trip_stats assumes the fields _direction_id_ and _shape_id_ exists, but according to the spec both fields are optional and the data sets I work with don't always use them.  Adding 
```
if not "direction_id" in f:
        f["direction_id"] = np.nan
if not "shape_id" in f:
        f["shape_id"] = np.nan
```
to the compute_trip_stats function seems to work, but I'm not sure if that's the best way to approach this problem

Thanks 

Dag

**Comment by araichev** [comment]
Thanks @dwastberg , i'll look into this today.

**Comment by araichev** [comment]
OK, pushed release 9.3.2, which fixes the issue.
Try that.
