### ISSUE TITLE
Enhancement: More informative "shape_dist_traveled decreases on a trip" error

### ISSUE THREAD

**Issue by PaschalisSk** [mrcagney/gtfstk#18]
In both stop_times and shapes we may have:

index | trip_id | stop_sequence | shape_dist_traveled
------ | ------- | ---------------- | ----------------------
1 | 1 | 1 | 0
2 | 1 | 2 | 3
3 | 1 | 3 | 1
4 | 1 | 4 | 2
5 | 1 | 5 | 5

With the current checks in validators.check_stop_times() and validators.check_shapes() we are only getting index 3 in the "shape_dist_traveled decreases on a trip" error.
In my opinion it would be more informative if we got both indices 3 and 4.

**Comment by araichev** [comment]
Meh, i'm not convinced the extra indices are more helpful.
It seems to me that the first index error is enough to alert the feed maintainer that they better fix the trip.
