### ISSUE TITLE
restrict_to_routes does not properly restrict transfers.txt

### ISSUE THREAD

**Issue by nlehuby** [mrcagney/gtfstk#20]
It you use `restrict_to_routes` to create a smaller GTFS from your original one, the `transfers.txt` file contains stops that are not referenced in `stops.txt`

**Comment by nlehuby** [comment]
to reproduce:

I've used this [GTFS](https://eu.ftp.opendatasoft.com/stif/GTFS/IDFM_gtfs.zip) with the following
```
route_ids_for_agency = list(feed.routes[feed.routes['agency_id']=="372"]['route_id'])	
little_feed = feed.restrict_to_routes(route_ids=route_ids_for_agency)	
gt.write_gtfs(little_feed, 'output/372.zip')
```

The ouput gtfs got 570 invalid values errors `Invalid value StopPoint:47:1766 in field from_stop_id
in line 4 of transfers.txt`

**Comment by araichev** [comment]
@nlehuby thanks for the report. Could you choose a smaller GTFS feed that witnesses the bug, something less than 10 MB? Your feed is 61 MB!

**Comment by araichev** [comment]
@nlehuby never mind. I found the error, fixed it, and tested it against your giant feed. New release out now. Give it a whirl.

**Comment by nlehuby** [comment]
Awesome :tada: Thanks!
